#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"


tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "IcPack" ; tput sgr0
echo ""
echo -e OBS:    Digite - IcPack - para acessar esse PACK
echo -e "\033[1;31m01\033[0m|\033[01;33m•-->\031[1;31m ConfVPS (CONFIGURA A VPS|SQUID3|) \033[0m"
echo -e "\033[1;31m02\033[0m|\033[01;33m•-->\033[1;34m UserCreate (Criar Usuarios SSH)\033[0m"
echo -e "\033[1;31m03\033[0m|\033[01;33m•-->\033[1;34m UserBackup (Gerencia Backup dos Usuarios SSH)\033[0m"
echo -e "\033[1;31m04\033[0m|\033[01;33m•-->\033[1;34m CpuMonitor (Monitora o Uso da CPU, RAM e UPTIME)\033[0m"
echo -e "\033[1;31m05\033[0m|\033[01;33m•-->\033[1;34m UserMonitor (Monitora os Usuarios Conectados)\033[0m"
echo -e "\033[1;31m06\033[0m|\033[01;33m•-->\033[1;34m DadosMonitor (Monitora o Uso de Dados/Banda|in||out|)\033[0m"
echo -e "\033[1;31m07\033[0m|\033[01;33m•-->\033[1;34m VNC (Ativa a Interface Gráfica no Servidor)\033[0m"
echo -e "\033[1;31m08\033[0m|\033[01;33m•-->\033[1;34m ClearCache (Limpa Cache e Swap da Maquina)\033[0m"
echo -e "\033[1;31m09\033[0m|\033[01;33m•-->\033[1;34m OpenUDP (Libera a Porta UDP para Ligacão e Jogos)\033[0m"
echo -e "\033[1;31m10\033[0m|\033[01;33m•-->\033[1;34m SpeedTest (Testa a Velocidade de Link do Servidor)\033[0m"
echo -e "\033[1;31m11\033[0m|\033[01;33m•-->\033[1;34m Banner (Mensagem para Usuario Quando Conectar)\033[0m"
echo -e "\033[1;31m12\033[0m|\033[01;33m•-->\033[1;34m LimiterSSH (Limita as Conexoes de Cada Usuario)\033[0m"
echo -e "\033[1;31m13\033[0m|\033[01;33m•-->\033[1;34m MudarLimite (Muda o Limite do Usuario)\033[0m"
echo -e "\033[1;31m14\033[0m|\033[01;33m•-->\033[1;34m MudarSenha (Muda a Senha do Usuario)\033[0m"
echo -e "\033[1;31m15\033[0m|\033[01;33m•-->\033[1;34m MudarValidade (Muda a Data de Validade do Usuario)\033[0m"
echo -e "\033[1;31m16\033[0m|\033[01;33m•-->\033[1;34m UserDel (Deleta Usuario)\033[0m"
echo -e "\033[1;31m17\033[0m|\033[01;33m•-->\033[1;34m addhost (Adiciona Novo Host ao Squid)\033[0m"
echo -e "\033[1;31m18\033[0m|\033[01;33m•-->\033[1;34m OpenVPN OI\033[0m""\033[0;31m[OFF]\033[0;31m""\033[01;33m(Configura e Gerencia Usuarios .ovpn)\033[0m"
echo -e "\033[1;31m19\033[0m|\033[01;33m•-->\033[1;34m OpenVPN VIVO\033[0m""\033[0;31m[OFF]\033[0;31m""\033[01;33m(Configura e Gerencia Usuarios .ovpn)\033[0m"
echo -e "\033[1;31m20\033[0m|\033[01;33m•-->\033[1;34m UserClear (Limpa Usuarios Vencidos)\033[0m"
echo -e "\033[1;31m21\033[0m|\033[01;33m•-->\033[1;34m KernelControl (Procura ATT para Kernel ou Remove)\033[0m"
echo -e "\033[1;31m22\033[0m|\033[01;33m•-->\033[1;34m SSHMonitor (Monitor Total de Usuarios Conectados)\033[0m"
echo -e "\033[1;31m23\033[0m|\033[01;33m•-->\033[1;34m Instala SOCKS (Instala na Porta 8080)\033[0m"
echo -e "\033[1;31m24\033[0m|\033[01;33m•-->\033[1;34m Tcptweaker (Melhora a velocidade e estabilidade da conexão Proxy)\033[0m"
echo""
echo""
read -p " Selecione uma opção (01 a 24): " opcao

case $opcao in
 01)
  ConfVPS
  sleep 4
  IcPack;;
 02)
  UserCreate
  sleep 5
  IcPack;;
 03)
  UserBackup
  sleep 5
  IcPack;;
 04)
  CpuMonitor;;
 05)
  UserMonitor;;
 06)
  DadosMonitor;;
 07)
  VNC
  sleep 8
  IcPack;;
 08)
  ClearCache
  sleep 4
  IcPack;;
 09)
  OpenUDP;;
 10)
  SpeedTest
  sleep 8
  IcPack;;
 11)
  Banner
  sleep 4
  IcPack;;
 12)
  LimiterSSH;;
 13)
  MudarLimite
  sleep 4
  IcPack;;
 14)
  MudarSenha
  sleep 4
  IcPack;;
 15)
  MudarValidade
  sleep 5
  IcPack;;
 16)
  UserDel
  sleep 4
  IcPack;;
 17)
  addhost
  sleep 4
  IcPack;;
 18)
  OpenVPN
  sleep 5
  IcPack;;
 19)
  OpenVPN2
  sleep 5
  IcPack;;
 20)
  UserClear
  sleep 3
  IcPack;;
 21)
  KernelControl
  sleep 2
  IcPack;;
 22)
  MonitorTotal
  sleep 20
  IcPack;;
 23)
  Socks.py
  sleep 5
  IcPack;;
 24)
  tcptweaker.sh
  sleep 5
  IcPack;;
esac
